### ISSUE TITLE
Optimise for iPad Pro?

### ISSUE THREAD

**Issue by lexrus** [kimar/swifton-exec#1]
:+1: Nice project.

And I'm expecting a remote Swift coding experience on iPad Pro. :smile:

**Comment by kimar** [comment]
Basic responsiveness is implemented now, also it's using Ace Editor provide syntax highlighting.
![kidmar_2015-dec-20](https://cloud.githubusercontent.com/assets/126418/11917722/55eb61da-a767-11e5-8a4a-c6c2c694b715.jpg)

**Comment by kimar** [comment]
Not sure if I'd call it "optimize" though...I'll leave this ticket open because we might need to optimize more...

**Comment by kimar** [comment]
This issue rather goes into `swifton-www` so I'm closing this one, here's the cross-reference: https://github.com/kimar/swifton-www/issues/3
