### ISSUE TITLE
Suggest autocompletion with SourceKitten

### ISSUE THREAD

**Issue by lexrus** [kimar/swifton-exec#2]
It'll be awesome to integrate [SourceKitten](https://github.com/jpsim/SourceKitten) and [Ace](https://github.com/ajaxorg/ace) to achieve both autocompletion and syntax highlight.

**Comment by kimar** [comment]
Ace is in now, SourceKitten still TBD

**Comment by kimar** [comment]
This rather goes into `swifton-www` so I'm cross referncing this and clsoing the issue here: https://github.com/kimar/swifton-www/issues/2
